### ISSUE TITLE
Problema com raiz quadrada

### ISSUE THREAD

**Issue by mateusabreu** [sitegui/editorHP#30]
Como faz para utilizar a raiz quadrada quando utilizar o modo de equação?

**Comment by sitegui** [comment]
Olá Mateus,

Havia um erro no validador de sintaxe de equações. Acabei de arruma-lo.

Respondendo sua pergunta: insira o símbolo com o menu de caracteres especiais ou use `\v/`.
Exemplos: `'\v/X'` ou `'1+\v/(X^2-7)'`

Abraço!
