### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [sitegui/editorHP#36]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by vcolella** [comment]
Olá ! 

Tudo indica que o repo está abandonado, mas nada nos impede de continuar o desenvolvimento a partir de um fork. Qual sua ideia ?

**Comment by ghost** [comment]
Oi vcolella 

> Olá !
> Tudo indica que o repo está abandonado, mas nada nos impede de continuar o desenvolvimento a partir de um fork. Qual sua ideia ?

- valeu pelo comentário.
- mas porque vou desenvolver algo se ninguém está interessado em contribuir? - esse é o mesmo problema que o ocorreu com ubuntu unity, ninguém estava interessado em continuar o ubuntu unity, e o projeto foi arquivado. o mesmo exemplo que dei do ubuntu unity, dou aqui. gostaria de continuar com esse projeto, mas se não houver interesse, arquivo.
- como você falou que o projeto foi abandonado, vou arquivar essa ideia.

**Comment by vcolella** [comment]
> * mas porque vou desenvolver algo se ninguém está interessado em contribuir? - esse é o mesmo problema que o ocorreu com ubuntu unity, ninguém estava interessado em continuar o ubuntu unity, e o projeto foi arquivado. o mesmo exemplo que dei do ubuntu unity, dou aqui. gostaria de continuar com esse projeto, mas se não houver interesse, arquivo.
> * como você falou que o projeto foi abandonado, vou arquivar essa ideia.

Bons pontos @codehangen !

Mas se você já tem as ideias, porque não apenas registrá-las para a posteridade ? 

Eu mesmo me interesso e consideraria contribuir por exemplo rsrs. De repente até o próprio @sitegui se interessa novamente e volta a investir no projeto !

No fim das contas alguma consideração ele deve ter, já que mantém o site rodando..

**Comment by ghost** [comment]
Oi vcolella.

> Bons pontos @codehangen !

valeu pelo comentário novamente.

> Mas se você já tem as ideias, porque não apenas registrá-las para a posteridade ?

- vou ser bem direto e espero que isso não represente nenhuma forma de falta de desrespeito. Veja...  o custo de manter software aberto é manutenção, suporte, comunidade, desenvolvimento, treinamento, documentação técnica. Tudo isso deve ser levado em conta em um projeto de código aberto. Não existe "almoço grátis", o custo de desenvolvimento de código aberto é esse. 
- Nesse sentido, não vale apena desenvolver algo aberto, se há um custo ali envolvido e não há retorno. 
- Entende-se por "custo ali envolvido e não há retorno" o tal do roi(retorno sobre investimento).
- por isso invisto meu tempo em coisas que possuem retorno e que a comunidade deseja. Não vale apena ajudar algo que não é do interesse de ninguém. É tempo e dia de vida perdido.
- um bom exemplo disso é a versão da ferramenta adobe para linux, já houve um entrevista com o algum desenvolvedor chefe que trabalha na Adobe, e uma das conversas foi essa. O projeto acabaria ali abandonado com vários custos envolvidos por nada.
- Mesmo se eles desenvolvesse uma versão da adobe no linux, não se sabe se haveria interesse da comunidade em contribuir. E se nesse caso, não houvesse o interesse em contribuir, não haveria porque liberar o código-fonte se ninguém se interessa por isso. 
- Além disso, há um problema de distribuição de software. Existem diversos gerenciadores de pacote ou módulo no linux, oferecer suporte a alguma desses gerenciadores de pacote ou módulo já é complicado e imagina selecionar por exemplo apenas ubuntu, debian etc e não arch-linux etc?
- se quiser outro exemplo, toda distro linux tem que ter comunidade e suporte, a distro linux que não possui comunidade e suporte acabam abandonadas. Claro que há exceções nos exemplos que citei, mas para a maior parte dos casos é essa.
- o que quero dizer com tudo isso, é que entendo seu ponto de vista, mas para a maior parte das pessoas esse tipo de pensamento não é o mais viável - porque não há retorno. até mesmo projetos abertos como "linux", "gnu utils" tem certo público-alvo e retorno seja das empresas ou comunidade. 
- e por mais que as pessoas digam que não, a realidade é outra.

> Eu mesmo me interesso e consideraria contribuir por exemplo rsrs. De repente até o próprio @sitegui se interessa novamente e volta a investir no projeto !

- agora sobre isso, nem sempre é verdade. um fork é nada mais ou nada menos que uma versão não oficial ou uma versão diferente da versão oficial. nem sempre a versão não oficial ganha destaque como é o caso do mariadb, geralmente os desenvolvedores utilizam o mysql e não o fork mariadb. com "exceções" verá algum projeto com mariadb. geralmente, nos meus projetos é mysql.
- claro que existe bons projetos com o mongodb, redis, couchdb ou postgres e até mesmo mariadb. mas o ponto que quero dizer é que nem sempre um fork é algo relevante do que um projeto oficial.

> No fim das contas alguma consideração ele deve ter, já que mantém o site rodando..

por isso que perguntei se o projeto estava em funcionamento, se estava ativo. minha esperança era alguma resposta nesse sentido, se o projeto está abandonado ou se ainda vale apena contribuir.

**Comment by vcolella** [comment]
@codehangen ,

> * um bom exemplo disso é a versão da ferramenta adobe para linux, já houve um entrevista com o CEO da Adobe, e uma das conversas foi essa. O projeto acabaria ali abandonado com vários custos envolvidos por nada.
> * Mesmo se eles desenvolvesse uma versão da adobe no linux, não se sabe se haveria interesse da comunidade em contribuir. E se nesse caso, não houvesse o interesse em contribuir, não haveria porque liberar o código-fonte se ninguém se interessa por isso.
> * Além disso, há um problema de distribuição de software. Existem diversos gerenciadores de pacote ou módulo no linux, oferecer suporte a alguma desses gerenciadores de pacote ou módulo já é complicado e imagina selecionar por exemplo apenas ubuntu, debian etc e não arch-linux etc?

Não sei se faz muito sentido a comparação nos seus exemplos com softwares de "grande escala", já que aqui estamos falando de uma ferramenta simples criada por um desenvolvedor solo para uma calculadora ultrapassada que nem o próprio fabricante continuou produzindo ou dando suporte. Mas entendo a sua mensagem !

> * vou ser bem direto e espero que isso não represente nenhuma forma de falta de desrespeito. Veja...  o custo de manter software aberto é manutenção, suporte, comunidade, desenvolvimento, treinamento, documentação técnica. Tudo isso deve ser levado em conta em um projeto de código aberto. Não existe "almoço grátis", o custo de desenvolvimento de código aberto é esse.
> * Nesse sentido, não vale apena desenvolver algo aberto, se há um custo ali envolvido e não há retorno.
> * por isso invisto meu tempo em coisas que possuem retorno e que a comunidade deseja. Não vale apena ajudar algo que não é do interesse de ninguém. É tempo e dia de vida perdido.

Você faz total sentido ! Concordo que nosso tempo é sempre melhor investido em algo que seja de valia para alguém.

> por isso que perguntei se o projeto estava em funcionamento, se estava ativo. minha esperança era alguma resposta nesse sentido, se o projeto está abandonado ou se ainda vale apena contribuir.

Entendo, respondi anteriormente imaginando que seriam apenas algumas sugestões rápidas.

De todo modo, obrigado pela troca de informações !

Sds

**Comment by ghost** [comment]
Oi vcolella.

> Você faz total sentido ! Concordo que nosso tempo é sempre melhor investido em algo que seja de valia para alguém.

- obrigado pelo teu comentário.
- o que você passou de feedback aqui, era exatamente isso que queria falar de forma simples, direta. 

> Não sei se faz muito sentido a comparação nos seus exemplos com softwares de "grande escala", já que aqui estamos falando de uma ferramenta simples criada por um desenvolvedor solo para uma calculadora ultrapassada que nem o próprio fabricante continuou produzindo ou dando suporte. Mas entendo a sua mensagem !

- existem várias coisas que podem ser feitas. por exemplo, nova interface gráfica, maior documentação técnica, bem como maior suporte.
- por exemplo, minha ideia era ajudar na parte ui/ux, minha "especialidade" é na parte frontend, disse "especialidade" porque é algo que gosto bastante e estudo e trabalho com isso de forma contínua, ainda não acho que tenho conhecimento profundo da área. 
- sobre o exemplo que dei o mesmo pode ser aplicado ao void-linux e diversos outras distro linux ou quaisquer outros softwares. poderia ter citado algo como llvm vs gcc etc. geralmente, alguns escolhem o llvm do que o gcc - mas isso é outro assunto. rs, exemplos não faltam.

> entendo, respondi anteriormente imaginando que seriam apenas algumas sugestões rápidas.
> De todo modo, obrigado pela troca de informações !
> Sds

- queria ajudar esse repositório ajudando na parte ui/ux. como foi arquivado, vou deixar essa ideia para lá.
- valeu pelo feedback, tenha um ótimo dia. até.
